# Generated by Django 3.0.4 on 2020-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_F', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_G', models.IntegerField()),
                ('id_F', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_L', models.IntegerField()),
                ('id_S', models.IntegerField()),
                ('cabinet', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_S', models.IntegerField()),
                ('id_G', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('teacher', models.CharField(max_length=120)),
            ],
        ),
    ]
